-- ============================================================================
-- HOTEL SAI INTERNATIONAL - MIGRATION 0005
-- AUTHENTIC CANNON KITCHEN MENU (85 ITEMS) & DAILY SALES AUDIT (23 & 24 SEP 2026)
-- ============================================================================

-- Ensure menu_items has item_code
-- 56. ITEM-WISE SALES REPORTS (MYSOFT / CANNON KITCHEN DAILY PRODUCT MIX)
CREATE TABLE IF NOT EXISTS daily_item_sales (
  record_id TEXT PRIMARY KEY,
  report_date TEXT NOT NULL,
  item_code TEXT NOT NULL,
  item_name TEXT NOT NULL,
  section TEXT NOT NULL,
  category TEXT NOT NULL,
  total_qty INTEGER NOT NULL,
  unit_rate REAL NOT NULL,
  sales_amount REAL NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- SEED 85 AUTHENTIC MENU ITEMS
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-116', '116', 'ANDHRA CHICKEN', 'Chicken Specialities', 260.00, 0, 0, 1, 'Spicy Andhra style country chicken roasted with crushed peppercorns and curry leaves.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-164', '164', 'APOLLO FISH', 'Mutton & Seafood', 350.00, 0, 0, 1, 'Boneless fish fillets marinated with spiced yogurt, deep fried and tempered in South Indian spices.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-229', '229', 'BABY CORN MASALA', 'Paneer & Veg Delicacies', 180.00, 1, 0, 0, 'Tender baby corn spears simmered in seasoned onion-tomato gravy.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-156', '156', 'BOILED EGG ( 2pcs)', 'Egg Delicacies', 60.00, 0, 0, 0, 'Two farm-fresh eggs hard boiled and served with rock salt and pepper.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-347', '347', 'BUTTER NAAN', 'Tandoori & Breads', 50.00, 1, 0, 0, 'Refined flour bread baked in tandoor and basted with generous melted butter.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-110', '110', 'CHICKEN CURRY', 'Chicken Specialities', 240.00, 0, 0, 0, 'Homestyle chicken cooked with aromatic Odisha spices in rich gravy.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-114', '114', 'CHICKEN DO-PYAZA', 'Chicken Specialities', 260.00, 0, 0, 0, 'Chicken pieces tossed with double the quantity of browned and cubed onions.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-306', '306', 'CHICKEN FRIED RICE', 'Rice & Biryani', 250.00, 0, 0, 0, 'Wok tossed long grain rice with tender diced chicken, eggs, and spring onions.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-21', '21', 'CHICKEN HOT & SOUR SOUP', 'Soups & Starters', 140.00, 0, 0, 0, 'Classic Indo-Chinese sour and peppery soup with shredded chicken.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-115', '115', 'CHICKEN HYDERABADI', 'Chicken Specialities', 260.00, 0, 0, 1, 'Rich chicken gravy enriched with fresh spinach, coriander, and mint puree.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-127', '127', 'CHICKEN KASHA', 'Chicken Specialities', 240.00, 0, 0, 1, 'Traditional slow-roasted semi-gravy chicken with caramelized onions and whole spices.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-290', '290', 'CHICKEN LOLLIPOP', 'Soups & Starters', 270.00, 0, 0, 1, 'Crisp fried chicken winglets tossed in fiery Schezwan glaze.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-140', '140', 'CHICKEN PATIALA', 'Chicken Specialities', 240.00, 0, 0, 0, 'Punjabi style creamy chicken preparation topped with egg omelette ribbon.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-125', '125', 'CHICKEN SANGRILLA', 'Chicken Specialities', 280.00, 0, 0, 1, 'Chef signature fusion boneless chicken wok tossed with bell peppers and sweet tangy sauce.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-131', '131', 'CHICKEN TIKKA MASALA', 'Chicken Specialities', 380.00, 0, 0, 1, 'Clay oven smoked chicken tikka chunks in luscious makhani tomato reduction.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-284', '284', 'CHICKEN WINGS', 'Soups & Starters', 260.00, 0, 0, 0, 'Crispy spiced marinated chicken wings served with hot garlic dip.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-119', '119', 'CHILLI CHICKEN', 'Soups & Starters', 250.00, 0, 0, 1, 'All-time favorite wok-tossed battered chicken with green chillies, garlic, and soy.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-33', '33', 'CHILLI MUSHROOM', 'Soups & Starters', 230.00, 1, 0, 1, 'Fresh Rayagada button mushrooms tossed with crunchy capsicum in chilli soy.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-28', '28', 'CHILLI PANEER', 'Soups & Starters', 220.00, 1, 0, 0, 'Cubes of tender paneer wok-fried with onions, capsicum, and oriental sauces.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-294', '294', 'CHILLI PRAWN', 'Mutton & Seafood', 350.00, 0, 0, 1, 'Succulent fresh prawns wok-tossed in spicy chilli garlic sauce.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-11', '11', 'CURD CUP', 'Rice & Accompaniments', 35.00, 1, 1, 0, 'Fresh chilled set curd.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-194', '194', 'CURD RICE', 'Rice & Biryani', 150.00, 1, 1, 0, 'Comforting south-style curd rice tempered with mustard, curry leaves, and pomegranate.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-191', '191', 'DAL FRY', 'Dal & Curries', 120.00, 1, 0, 0, 'Yellow toor lentils cooked smooth and tempered with cumin, garlic, and ghee.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-335', '335', 'DAL KHICHDI', 'Rice & Biryani', 180.00, 1, 1, 0, 'Wholesome rice and yellow lentil porridge simmered with mild spices and ghee.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-198', '198', 'DAL TADAKA', 'Dal & Curries', 150.00, 1, 0, 0, 'Double tempered lentils with dried red chillies, garlic, and smoky hing.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-153', '153', 'EGG CURRY', 'Egg Delicacies', 260.00, 0, 0, 0, 'Hard boiled eggs simmered in spicy masala gravy.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-159', '159', 'EGG FRIED RICE', 'Rice & Biryani', 210.00, 0, 0, 0, 'Fragrant rice stir-fried with scrambled eggs, scallions, and pepper.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-691', '691', 'EGG FRY', 'Egg Delicacies', 190.00, 0, 0, 0, 'Pan-seared spiced eggs with onions and green chillies.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-85', '85', 'EGG POACH / FRIED EGG', 'Egg Delicacies', 100.00, 0, 0, 0, 'Fresh sunny side up or poached egg.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-215', '215', 'EGG TADKA', 'Egg Delicacies', 180.00, 0, 0, 0, 'Dhaba style green moong lentils scrambled with spiced eggs.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-39', '39', 'FINGER CHIPS', 'Soups & Starters', 150.00, 1, 1, 0, 'Golden crispy french fries served with ketchup.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-167', '167', 'FISH FRY / ROST', 'Mutton & Seafood', 200.00, 0, 0, 1, 'Coastal spiced rava/masala fried freshwater fish darnes.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-232', '232', 'FRY PAPAD', 'Rice & Accompaniments', 30.00, 1, 1, 0, 'Deep fried crunchy urad dal papad.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-563', '563', 'GAIL BREAKFAST', 'GAIL Corporate Meals', 250.00, 1, 0, 1, 'Corporate executive breakfast buffet box contracted for GAIL India regional personnel.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-568', '568', 'GAIL N V DINNER', 'GAIL Corporate Meals', 480.00, 0, 0, 1, 'Special corporate non-veg dinner thali with chicken curry, breads, rice, and sweet.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-565', '565', 'GAIL N V LUNCH', 'GAIL Corporate Meals', 480.00, 0, 0, 1, 'Full corporate non-veg executive lunch spread for GAIL pipeline officers.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-566', '566', 'GAIL SNACKS', 'GAIL Corporate Meals', 170.00, 1, 0, 1, 'Evening tea-time hot savory snacks box for GAIL corporate desk.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-567', '567', 'GAIL VEG DINNER', 'GAIL Corporate Meals', 370.00, 1, 0, 1, 'Balanced vegetarian corporate dinner spread with paneer, dal, sabzi, phulkas, and rice.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-564', '564', 'GAIL VEG LUNCH', 'GAIL Corporate Meals', 370.00, 1, 0, 1, 'Executive vegetarian lunch box for visiting GAIL project engineers.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-192', '192', 'GARDEN FRESH SALAD', 'Rice & Accompaniments', 80.00, 1, 1, 0, 'Sliced cucumber, carrots, tomatoes, onions, and green chillies with lemon.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-287', '287', 'GARLIC CHICKEN', 'Chicken Specialities', 250.00, 0, 0, 0, 'Chicken cubes tossed with abundant roasted garlic and oriental seasonings.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-349', '349', 'GARLIC NAAN', 'Tandoori & Breads', 80.00, 1, 0, 1, 'Tandoor naan topped with minced roasted garlic, coriander, and butter.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-246', '246', 'GREEN PEAS FRY', 'Paneer & Veg Delicacies', 180.00, 1, 1, 0, 'Tender green peas sauteed with light cumin, ginger, and mild spices.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-30', '30', 'GREEN PEAS MASALA', 'Paneer & Veg Delicacies', 200.00, 1, 1, 0, 'Green peas simmered in a spiced onion-tomato gravy.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-181', '181', 'KADAI PANEER', 'Paneer & Veg Delicacies', 240.00, 1, 0, 1, 'Cottage cheese and bell peppers cooked in freshly pounded coriander-chilli kadai masala.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-157', '157', 'MASALA OMELETTE', 'Egg Delicacies', 120.00, 0, 0, 0, 'Two eggs whisked with chopped onions, tomatoes, chillies, and pan-fried.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-36', '36', 'MASALA PAPAD', 'Rice & Accompaniments', 40.00, 1, 0, 0, 'Crispy roasted papad topped with tangy spiced onion, tomato, and coriander kachumber.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-175', '175', 'MIX VEG CURRY', 'Paneer & Veg Delicacies', 220.00, 1, 0, 0, 'Medley of seasonal vegetables cooked in traditional semi-dry curry gravy.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-305', '305', 'MIXED FRIED RICE', 'Rice & Biryani', 300.00, 0, 0, 0, 'Wok-tossed rice with chicken, prawns, eggs, and crisp vegetables.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-266', '266', 'MUSHROOM DO PYAZA', 'Paneer & Veg Delicacies', 240.00, 1, 0, 1, 'Rayagada button mushrooms cooked with caramelized and diced onion chunks.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-95', '95', 'MUTTON CURRY', 'Mutton & Seafood', 370.00, 0, 0, 1, 'Tender goat meat slow simmered in traditional Odisha spicy clove and cinnamon gravy.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-219', '219', 'PANEER BHARTHA', 'Paneer & Veg Delicacies', 240.00, 1, 0, 0, 'Freshly grated paneer cooked with green peas, tomatoes, and home spices.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-179', '179', 'PANEER BUTTER MASALA', 'Paneer & Veg Delicacies', 240.00, 1, 0, 1, 'Soft paneer cubes simmered in velvety butter tomato gravy.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-222', '222', 'PANEER KAJU CURRY', 'Paneer & Veg Delicacies', 240.00, 1, 0, 1, 'Paneer cubes and roasted whole cashews simmered in a luscious creamy gravy.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-183', '183', 'PANEER SHAHI KORMA', 'Paneer & Veg Delicacies', 270.00, 1, 1, 1, 'Royal white gravy preparation with paneer, melon seeds, and fragrant saffron.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-348', '348', 'PHULKA', 'Tandoori & Breads', 30.00, 1, 1, 0, 'Puffed whole wheat phulka made fresh on tawa.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-211', '211', 'PLAIN DAL', 'Dal & Curries', 100.00, 1, 1, 0, 'Simple boiled yellow lentils with pinch of turmeric and salt.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-61', '61', 'ROASTED PAPAD', 'Rice & Accompaniments', 25.00, 1, 1, 0, 'Fire roasted light papad.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-247', '247', 'SALT & PAPPER MUSHROOM', 'Soups & Starters', 230.00, 1, 0, 1, 'Crispy fried mushrooms tossed with freshly ground pepper and sea salt.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-54', '54', 'SALT & PEPPER CORN', 'Soups & Starters', 220.00, 1, 0, 0, 'Crispy american sweet corn kernels tossed with cracked pepper and scallions.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-88', '88', 'SALT & PEPPER PRAWN', 'Mutton & Seafood', 350.00, 0, 0, 1, 'Golden fried prawns dusted with salt, crushed black pepper, and garlic.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-120', '120', 'SPL CHICKEN FRIED RICE', 'Rice & Biryani', 300.00, 0, 0, 1, 'Cannon Kitchen special fried rice with double chicken chunks and chef secret sauce.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-307', '307', 'STEAM RICE', 'Rice & Biryani', 80.00, 1, 1, 0, 'Steamed aromatic long grain rice.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-346', '346', 'TANDOORI ROTI', 'Tandoori & Breads', 40.00, 1, 0, 0, 'Traditional clay oven whole wheat bread.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-343', '343', 'TANGDI KABAB ( 3Pcs )', 'Chicken Specialities', 450.00, 0, 0, 1, 'Chicken drumsticks marinated in rich cashew paste and tandoori spices, char-grilled.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-142', '142', 'TANGIDI MASALA', 'Chicken Specialities', 500.00, 0, 0, 1, 'Roasted chicken drumsticks simmered in spiced thick brown masala gravy.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-341', '341', 'TD. CHICKEN ( Full )', 'Chicken Specialities', 500.00, 0, 0, 1, 'Whole spring chicken marinated overnight and roasted in traditional tandoor.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-109', '109', 'TD. CHICKEN ( Half )', 'Chicken Specialities', 300.00, 0, 0, 1, 'Half spring chicken roasted to smoky perfection in clay oven.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-312', '312', 'VEG FRIED RICE', 'Rice & Biryani', 180.00, 1, 0, 0, 'Classic wok-tossed basmati rice with finely diced carrots, beans, and cabbage.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-188', '188', 'VEG JALFREZI', 'Paneer & Veg Delicacies', 200.00, 1, 0, 0, 'Stir-fried seasonal vegetables in tangy spicy tomato-onion masala.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-217', '217', 'VEG KHAJANA', 'Paneer & Veg Delicacies', 250.00, 1, 0, 1, 'Assorted garden vegetables and paneer simmered in chef signature two-tone gravy.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-18', '18', 'VEG MANCHOW SOUP', 'Soups & Starters', 120.00, 1, 0, 0, 'Spicy garlic-flavored dark vegetable soup topped with crispy fried noodles.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-27', '27', 'VEG MANCHURIAN', 'Soups & Starters', 220.00, 1, 0, 0, 'Crispy vegetable dumplings tossed in ginger, garlic, and dark soy gravy.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-42', '42', 'VEG NOODLES', 'Rice & Biryani', 200.00, 1, 0, 0, 'Hakka style wok-tossed noodles with shredded vegetables and white pepper.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-336', '336', 'VEG PULAO', 'Rice & Biryani', 150.00, 1, 1, 0, 'Fragrant basmati rice gently cooked with green peas, carrots, and whole spices.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-364', '364', 'BLACK TEA', 'Beverages', 25.00, 1, 1, 0, 'Pure brewed black tea with lemon wedge.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-372', '372', 'COLD DRINKS 200ml', 'Beverages', 25.00, 1, 1, 0, 'Chilled carbonated soft drinks bottle.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-367', '367', 'FRESH LIME SODA', 'Beverages', 40.00, 1, 1, 0, 'Freshly squeezed lime juice with sparkling club soda (sweet/salt/mixed).', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-654', '654', 'GAIL COFFEE', 'GAIL Corporate Meals', 15.00, 1, 1, 1, 'Hot filtered coffee served for GAIL corporate desk meetings.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-653', '653', 'GAIL TEA', 'GAIL Corporate Meals', 15.00, 1, 1, 1, 'Freshly brewed milk tea for GAIL corporate office staff.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-375', '375', 'MASALA COLD DRINK', 'Beverages', 40.00, 1, 1, 0, 'Chilled cola spiked with black salt, roasted cumin, and lemon.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-212', '212', 'MILK HOT OR COLD', 'Beverages', 60.00, 1, 1, 0, 'Glass of pure Rayagada dairy milk (hot or chilled).', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-373', '373', 'PACKED DRINK WATER', 'Beverages', 20.00, 1, 1, 0, 'Packaged sealed mineral water 1-litre bottle.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-374', '374', 'SODA 750ml', 'Beverages', 40.00, 1, 1, 0, 'Chilled 750ml soda pet bottle.', 1);
INSERT OR REPLACE INTO menu_items (item_id, item_code, name, category, price, is_veg, is_jain, is_special, description, is_available) VALUES ('MENU-1', '1', 'TEA', 'Beverages', 30.00, 1, 1, 0, 'Signature hot masala milk tea brewed with cardamom and ginger.', 1);

-- SEED 85 AUTHENTIC ITEM-WISE SALES ENTRIES FOR 2026-09-24
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-116', '2026-09-24', '116', 'ANDHRA CHICKEN', 'FOOD', 'Chicken Specialities', 1, 260.00, 260.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-164', '2026-09-24', '164', 'APOLLO FISH', 'FOOD', 'Mutton & Seafood', 1, 350.00, 350.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-229', '2026-09-24', '229', 'BABY CORN MASALA', 'FOOD', 'Paneer & Veg Delicacies', 1, 180.00, 180.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-156', '2026-09-24', '156', 'BOILED EGG ( 2pcs)', 'FOOD', 'Egg Delicacies', 1, 60.00, 60.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-347', '2026-09-24', '347', 'BUTTER NAAN', 'FOOD', 'Tandoori & Breads', 34, 50.00, 1745.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-110', '2026-09-24', '110', 'CHICKEN CURRY', 'FOOD', 'Chicken Specialities', 2, 240.00, 480.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-114', '2026-09-24', '114', 'CHICKEN DO-PYAZA', 'FOOD', 'Chicken Specialities', 2, 260.00, 520.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-306', '2026-09-24', '306', 'CHICKEN FRIED RICE', 'FOOD', 'Rice & Biryani', 2, 250.00, 500.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-21', '2026-09-24', '21', 'CHICKEN HOT & SOUR SOUP', 'FOOD', 'Soups & Starters', 2, 140.00, 280.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-115', '2026-09-24', '115', 'CHICKEN HYDERABADI', 'FOOD', 'Chicken Specialities', 6, 260.00, 1560.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-127', '2026-09-24', '127', 'CHICKEN KASHA', 'FOOD', 'Chicken Specialities', 1, 240.00, 240.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-290', '2026-09-24', '290', 'CHICKEN LOLLIPOP', 'FOOD', 'Soups & Starters', 2, 270.00, 540.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-140', '2026-09-24', '140', 'CHICKEN PATIALA', 'FOOD', 'Chicken Specialities', 1, 240.00, 240.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-125', '2026-09-24', '125', 'CHICKEN SANGRILLA', 'FOOD', 'Chicken Specialities', 4, 280.00, 1120.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-131', '2026-09-24', '131', 'CHICKEN TIKKA MASALA', 'FOOD', 'Chicken Specialities', 1, 380.00, 380.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-284', '2026-09-24', '284', 'CHICKEN WINGS', 'FOOD', 'Soups & Starters', 1, 260.00, 260.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-119', '2026-09-24', '119', 'CHILLI CHICKEN', 'FOOD', 'Soups & Starters', 4, 250.00, 1000.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-33', '2026-09-24', '33', 'CHILLI MUSHROOM', 'FOOD', 'Soups & Starters', 6, 230.00, 1380.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-28', '2026-09-24', '28', 'CHILLI PANEER', 'FOOD', 'Soups & Starters', 1, 220.00, 220.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-294', '2026-09-24', '294', 'CHILLI PRAWN', 'FOOD', 'Mutton & Seafood', 1, 350.00, 350.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-11', '2026-09-24', '11', 'CURD CUP', 'FOOD', 'Rice & Accompaniments', 1, 35.00, 35.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-194', '2026-09-24', '194', 'CURD RICE', 'FOOD', 'Rice & Biryani', 4, 150.00, 600.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-191', '2026-09-24', '191', 'DAL FRY', 'FOOD', 'Dal & Curries', 8, 120.00, 960.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-335', '2026-09-24', '335', 'DAL KHICHDI', 'FOOD', 'Rice & Biryani', 2, 180.00, 360.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-198', '2026-09-24', '198', 'DAL TADAKA', 'FOOD', 'Dal & Curries', 2, 150.00, 300.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-153', '2026-09-24', '153', 'EGG CURRY', 'FOOD', 'Egg Delicacies', 1, 260.00, 260.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-159', '2026-09-24', '159', 'EGG FRIED RICE', 'FOOD', 'Rice & Biryani', 2, 210.00, 420.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-691', '2026-09-24', '691', 'EGG FRY', 'FOOD', 'Egg Delicacies', 6, 190.00, 1140.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-85', '2026-09-24', '85', 'EGG POACH / FRIED EGG', 'FOOD', 'Egg Delicacies', 1, 100.00, 100.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-215', '2026-09-24', '215', 'EGG TADKA', 'FOOD', 'Egg Delicacies', 1, 180.00, 180.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-39', '2026-09-24', '39', 'FINGER CHIPS', 'FOOD', 'Soups & Starters', 1, 150.00, 150.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-167', '2026-09-24', '167', 'FISH FRY / ROST', 'FOOD', 'Mutton & Seafood', 2, 200.00, 400.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-232', '2026-09-24', '232', 'FRY PAPAD', 'FOOD', 'Rice & Accompaniments', 2, 30.00, 60.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-563', '2026-09-24', '563', 'GAIL BREAKFAST', 'FOOD', 'GAIL Corporate Meals', 19, 250.00, 4750.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-568', '2026-09-24', '568', 'GAIL N V DINNER', 'FOOD', 'GAIL Corporate Meals', 16, 480.00, 7680.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-565', '2026-09-24', '565', 'GAIL N V LUNCH', 'FOOD', 'GAIL Corporate Meals', 10, 480.00, 4800.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-566', '2026-09-24', '566', 'GAIL SNACKS', 'FOOD', 'GAIL Corporate Meals', 21, 170.00, 3570.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-567', '2026-09-24', '567', 'GAIL VEG DINNER', 'FOOD', 'GAIL Corporate Meals', 9, 370.00, 3330.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-564', '2026-09-24', '564', 'GAIL VEG LUNCH', 'FOOD', 'GAIL Corporate Meals', 5, 370.00, 1850.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-192', '2026-09-24', '192', 'GARDEN FRESH SALAD', 'FOOD', 'Rice & Accompaniments', 6, 80.00, 480.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-287', '2026-09-24', '287', 'GARLIC CHICKEN', 'FOOD', 'Chicken Specialities', 1, 250.00, 250.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-349', '2026-09-24', '349', 'GARLIC NAAN', 'FOOD', 'Tandoori & Breads', 6, 80.00, 480.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-246', '2026-09-24', '246', 'GREEN PEAS FRY', 'FOOD', 'Paneer & Veg Delicacies', 2, 180.00, 360.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-30', '2026-09-24', '30', 'GREEN PEAS MASALA', 'FOOD', 'Paneer & Veg Delicacies', 1, 200.00, 200.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-181', '2026-09-24', '181', 'KADAI PANEER', 'FOOD', 'Paneer & Veg Delicacies', 1, 240.00, 240.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-157', '2026-09-24', '157', 'MASALA OMELETTE', 'FOOD', 'Egg Delicacies', 5, 120.00, 600.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-36', '2026-09-24', '36', 'MASALA PAPAD', 'FOOD', 'Rice & Accompaniments', 17, 40.00, 680.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-175', '2026-09-24', '175', 'MIX VEG CURRY', 'FOOD', 'Paneer & Veg Delicacies', 3, 220.00, 756.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-305', '2026-09-24', '305', 'MIXED FRIED RICE', 'FOOD', 'Rice & Biryani', 2, 300.00, 600.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-266', '2026-09-24', '266', 'MUSHROOM DO PYAZA', 'FOOD', 'Paneer & Veg Delicacies', 1, 240.00, 240.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-95', '2026-09-24', '95', 'MUTTON CURRY', 'FOOD', 'Mutton & Seafood', 3, 370.00, 1110.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-219', '2026-09-24', '219', 'PANEER BHARTHA', 'FOOD', 'Paneer & Veg Delicacies', 1, 240.00, 240.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-179', '2026-09-24', '179', 'PANEER BUTTER MASALA', 'FOOD', 'Paneer & Veg Delicacies', 3, 240.00, 720.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-222', '2026-09-24', '222', 'PANEER KAJU CURRY', 'FOOD', 'Paneer & Veg Delicacies', 4, 240.00, 960.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-183', '2026-09-24', '183', 'PANEER SHAHI KORMA', 'FOOD', 'Paneer & Veg Delicacies', 1, 270.00, 270.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-348', '2026-09-24', '348', 'PHULKA', 'FOOD', 'Tandoori & Breads', 28, 30.00, 840.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-211', '2026-09-24', '211', 'PLAIN DAL', 'FOOD', 'Dal & Curries', 1, 100.00, 100.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-61', '2026-09-24', '61', 'ROASTED PAPAD', 'FOOD', 'Rice & Accompaniments', 12, 25.00, 300.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-247', '2026-09-24', '247', 'SALT & PAPPER MUSHROOM', 'FOOD', 'Soups & Starters', 3, 230.00, 690.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-54', '2026-09-24', '54', 'SALT & PEPPER CORN', 'FOOD', 'Soups & Starters', 5, 220.00, 1100.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-88', '2026-09-24', '88', 'SALT & PEPPER PRAWN', 'FOOD', 'Mutton & Seafood', 3, 350.00, 1050.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-120', '2026-09-24', '120', 'SPL CHICKEN FRIED RICE', 'FOOD', 'Rice & Biryani', 2, 300.00, 600.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-307', '2026-09-24', '307', 'STEAM RICE', 'FOOD', 'Rice & Biryani', 11, 80.00, 880.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-346', '2026-09-24', '346', 'TANDOORI ROTI', 'FOOD', 'Tandoori & Breads', 13, 40.00, 520.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-343', '2026-09-24', '343', 'TANGDI KABAB ( 3Pcs )', 'FOOD', 'Chicken Specialities', 4, 450.00, 1800.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-142', '2026-09-24', '142', 'TANGIDI MASALA', 'FOOD', 'Chicken Specialities', 1, 500.00, 500.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-341', '2026-09-24', '341', 'TD. CHICKEN ( Full )', 'FOOD', 'Chicken Specialities', 1, 500.00, 500.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-109', '2026-09-24', '109', 'TD. CHICKEN ( Half )', 'FOOD', 'Chicken Specialities', 4, 300.00, 1200.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-312', '2026-09-24', '312', 'VEG FRIED RICE', 'FOOD', 'Rice & Biryani', 9, 180.00, 1620.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-188', '2026-09-24', '188', 'VEG JALFREZI', 'FOOD', 'Paneer & Veg Delicacies', 1, 200.00, 200.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-217', '2026-09-24', '217', 'VEG KHAJANA', 'FOOD', 'Paneer & Veg Delicacies', 1, 250.00, 250.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-18', '2026-09-24', '18', 'VEG MANCHOW SOUP', 'FOOD', 'Soups & Starters', 3, 120.00, 360.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-27', '2026-09-24', '27', 'VEG MANCHURIAN', 'FOOD', 'Soups & Starters', 3, 220.00, 660.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-42', '2026-09-24', '42', 'VEG NOODLES', 'FOOD', 'Rice & Biryani', 3, 200.00, 600.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-336', '2026-09-24', '336', 'VEG PULAO', 'FOOD', 'Rice & Biryani', 1, 150.00, 150.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-364', '2026-09-24', '364', 'BLACK TEA', 'BEVERAGE', 'Beverages', 2, 25.00, 50.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-372', '2026-09-24', '372', 'COLD DRINKS 200ml', 'BEVERAGE', 'Beverages', 6, 25.00, 150.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-367', '2026-09-24', '367', 'FRESH LIME SODA', 'BEVERAGE', 'Beverages', 12, 40.00, 480.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-654', '2026-09-24', '654', 'GAIL COFFEE', 'BEVERAGE', 'GAIL Corporate Meals', 19, 15.00, 285.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-653', '2026-09-24', '653', 'GAIL TEA', 'BEVERAGE', 'GAIL Corporate Meals', 59, 15.00, 885.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-375', '2026-09-24', '375', 'MASALA COLD DRINK', 'BEVERAGE', 'Beverages', 5, 40.00, 200.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-212', '2026-09-24', '212', 'MILK HOT OR COLD', 'BEVERAGE', 'Beverages', 1, 60.00, 60.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-373', '2026-09-24', '373', 'PACKED DRINK WATER', 'BEVERAGE', 'Beverages', 38, 20.00, 760.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-374', '2026-09-24', '374', 'SODA 750ml', 'BEVERAGE', 'Beverages', 2, 40.00, 80.00);
INSERT OR REPLACE INTO daily_item_sales (record_id, report_date, item_code, item_name, section, category, total_qty, unit_rate, sales_amount) VALUES ('DIS-20260924-1', '2026-09-24', '1', 'TEA', 'BEVERAGE', 'Beverages', 6, 30.00, 180.00);

-- SEED AUTHENTIC NIGHT AUDITS (23-SEP-2026 & 24-SEP-2026)
INSERT OR REPLACE INTO night_audits (
  audit_id, audit_date, total_rooms, occupied_rooms, occupancy_rate,
  room_revenue, pos_fnb_revenue, other_revenue, total_revenue,
  cash_collected, upi_collected, card_collected, corporate_billed,
  discrepancy_amount, auditor_name, notes
) VALUES
('NA-2026-09-23', '2026-09-23', 39, 20, 51.3, 49689.00, 27679.00, 0.00, 77368.00, 24898.00, 0.00, 0.00, 52470.00, 0.00, 'Sudhakar Reddy (Front Office Lead)', 'Verified 23-Sep-2026: Room Revenue ₹49,689.00, F&B Sales ₹27,679.00. Total Sales ₹77,368.00, Cash Collected ₹24,898.00.'),
('NA-2026-09-24', '2026-09-24', 39, 18, 46.2, 42150.00, 29049.00, 0.00, 71199.00, 4866.00, 20790.00, 0.00, 45543.00, 0.00, 'Sudhakar Reddy (Front Office Lead)', 'Verified 24-Sep-2026: Room Revenue ₹42,150.00, F&B Sales ₹29,049.00. Total Sales ₹71,199.00. Cash ₹4,866.00, Bank/UPI ₹20,790.00, Total Collections ₹25,656.00.');

-- SEED AUTHENTIC NIGHT AUDIT LOGS (23-SEP-2026 & 24-SEP-2026)
INSERT OR REPLACE INTO night_audit_log (
  audit_id, business_date, total_rooms, occupied_rooms, occupancy_pct,
  adr, revpar, room_revenue, fnb_revenue, other_revenue,
  gross_revenue, cash_collected, upi_collected, card_collected,
  company_billed, cash_opening_float, cash_expected, cash_physical_drawer,
  cash_variance, is_locked, auditor_name, notes
) VALUES
('NAL-2026-09-23', '2026-09-23', 39, 20, 51.3, 2484.45, 1274.08, 49689.00, 27679.00, 0.00, 77368.00, 24898.00, 0.00, 0.00, 52470.00, 5000.00, 29898.00, 29898.00, 0.00, 1, 'Sudhakar Reddy (Front Office Lead)', 'Verified 23-Sep-2026 Night Audit Hard-Lock.'),
('NAL-2026-09-24', '2026-09-24', 39, 18, 46.2, 2341.67, 1080.77, 42150.00, 29049.00, 0.00, 71199.00, 4866.00, 20790.00, 0.00, 45543.00, 5000.00, 9866.00, 9866.00, 0.00, 1, 'Sudhakar Reddy (Front Office Lead)', 'Verified 24-Sep-2026 Night Audit Hard-Lock.');
